//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTrackingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDebit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDebit()
        {
            this.tblDebitedStock = new HashSet<tblDebitedStock>();
        }
    
        public int debitID { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<int> personID { get; set; }
        public Nullable<int> departmentID { get; set; }
    
        public virtual tblDepartment tblDepartment { get; set; }
        public virtual tblPersons tblPersons { get; set; }
        public virtual tblProducts tblProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDebitedStock> tblDebitedStock { get; set; }
    }
}
