//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTrackingSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProducts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProducts()
        {
            this.tblDebit = new HashSet<tblDebit>();
            this.tblStock = new HashSet<tblStock>();
        }
    
        public int productID { get; set; }
        public string productName { get; set; }
        public Nullable<decimal> productPurchasePrice { get; set; }
        public Nullable<System.DateTime> productPurchaseDate { get; set; }
        public string productType { get; set; }
        public Nullable<bool> productActivity { get; set; }
        public string purchasedCompany { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDebit> tblDebit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStock> tblStock { get; set; }
    }
}
